2024-06-27 08:12:57,221 - distributed.nanny - INFO -         Start Nanny at: 'tcp://128.117.208.62:38251'
2024-06-27 08:13:00,933 - distributed.worker - INFO -       Start worker at: tcp://128.117.208.62:33067
2024-06-27 08:13:00,933 - distributed.worker - INFO -          Listening to: tcp://128.117.208.62:33067
2024-06-27 08:13:00,933 - distributed.worker - INFO -           Worker name:               PBSCluster-0
2024-06-27 08:13:00,933 - distributed.worker - INFO -          dashboard at:       128.117.208.62:37611
2024-06-27 08:13:00,934 - distributed.worker - INFO - Waiting to connect to: tcp://128.117.208.86:37311
2024-06-27 08:13:00,934 - distributed.worker - INFO - -------------------------------------------------
2024-06-27 08:13:00,934 - distributed.worker - INFO -               Threads:                          1
2024-06-27 08:13:00,934 - distributed.worker - INFO -                Memory:                   3.73 GiB
2024-06-27 08:13:00,934 - distributed.worker - INFO -       Local Directory: /glade/derecho/scratch/mdfowler/tmp/dask-scratch-space/worker-ttrllwmi
2024-06-27 08:13:00,934 - distributed.worker - INFO - -------------------------------------------------
2024-06-27 08:13:18,569 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-06-27 08:13:18,571 - distributed.worker - INFO -         Registered to: tcp://128.117.208.86:37311
2024-06-27 08:13:18,571 - distributed.worker - INFO - -------------------------------------------------
2024-06-27 08:13:18,572 - distributed.core - INFO - Starting established connection to tcp://128.117.208.86:37311
2024-06-27 08:13:43,712 - distributed.core - INFO - Event loop was unresponsive in Worker for 7.69s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-06-27 09:14:50,014 - distributed.worker.memory - WARNING - Worker is at 92% memory usage. Pausing worker.  Process memory: 3.45 GiB -- Worker memory limit: 3.73 GiB
2024-06-27 09:14:50,723 - distributed.worker.memory - WARNING - Worker is at 48% memory usage. Resuming worker. Process memory: 1.81 GiB -- Worker memory limit: 3.73 GiB
2024-06-27 09:17:47,919 - distributed.nanny.memory - WARNING - Worker tcp://128.117.208.62:33067 (pid=19958) exceeded 95% memory budget. Restarting...
2024-06-27 09:17:47,947 - distributed.nanny - INFO - Worker process 19958 was killed by signal 15
2024-06-27 09:17:47,952 - distributed.nanny - WARNING - Restarting worker
2024-06-27 09:17:51,266 - distributed.worker - INFO -       Start worker at: tcp://128.117.208.62:43513
2024-06-27 09:17:51,270 - distributed.worker - INFO -          Listening to: tcp://128.117.208.62:43513
2024-06-27 09:17:51,270 - distributed.worker - INFO -           Worker name:               PBSCluster-0
2024-06-27 09:17:51,270 - distributed.worker - INFO -          dashboard at:       128.117.208.62:34823
2024-06-27 09:17:51,270 - distributed.worker - INFO - Waiting to connect to: tcp://128.117.208.86:37311
2024-06-27 09:17:51,270 - distributed.worker - INFO - -------------------------------------------------
2024-06-27 09:17:51,270 - distributed.worker - INFO -               Threads:                          1
2024-06-27 09:17:51,270 - distributed.worker - INFO -                Memory:                   3.73 GiB
2024-06-27 09:17:51,270 - distributed.worker - INFO -       Local Directory: /glade/derecho/scratch/mdfowler/tmp/dask-scratch-space/worker-fxc5ivr9
2024-06-27 09:17:51,270 - distributed.worker - INFO - -------------------------------------------------
2024-06-27 09:17:55,749 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-06-27 09:17:55,751 - distributed.worker - INFO -         Registered to: tcp://128.117.208.86:37311
2024-06-27 09:17:55,751 - distributed.worker - INFO - -------------------------------------------------
2024-06-27 09:17:55,752 - distributed.core - INFO - Starting established connection to tcp://128.117.208.86:37311
2024-06-27 10:54:33,512 - distributed.worker - ERROR - Worker stream died during communication: tcp://128.117.208.106:45739
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/comm/core.py", line 342, in connect
    comm = await wait_for(
           ^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/utils.py", line 1935, in wait_for
    return await fut
           ^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/comm/tcp.py", line 560, in connect
    convert_stream_closed_error(self, e)
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x1511bea8bc10>: ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/worker.py", line 2056, in gather_dep
    response = await get_data_from_worker(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/worker.py", line 2857, in get_data_from_worker
    comm = await rpc.connect(worker)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/core.py", line 1619, in connect
    return await self._connect(addr=addr, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/core.py", line 1563, in _connect
    comm = await connect(
           ^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/comm/core.py", line 368, in connect
    raise OSError(
OSError: Timed out trying to connect to tcp://128.117.208.106:45739 after 30 s
2024-06-27 11:01:23,510 - distributed.core - INFO - Connection to tcp://128.117.208.86:37311 has been closed.
2024-06-27 11:01:23,512 - distributed.worker - INFO - Stopping worker at tcp://128.117.208.62:43513. Reason: worker-handle-scheduler-connection-broken
2024-06-27 11:01:23,517 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://128.117.208.62:38251'. Reason: worker-handle-scheduler-connection-broken
2024-06-27 11:01:23,523 - distributed.nanny - INFO - Worker closed
2024-06-27 11:01:27,324 - distributed.nanny - INFO - Closing Nanny at 'tcp://128.117.208.62:38251'. Reason: nanny-close-gracefully
2024-06-27 11:01:27,325 - distributed.dask_worker - INFO - End worker
